// Copyright (c) 2026 Meheraj. Use of this source code is governed by the
// MIT license that can be found in the LICENSE file.
//
// Autogenerated from Pigeon, do not edit directly.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class SmsMessageData {
  SmsMessageData({
    required this.id,
    required this.address,
    required this.body,
    required this.dateMillis,
    this.dateSentMillis,
    this.subscriptionId,
    this.threadId,
    required this.isRead,
  });

  int id;

  String address;

  String body;

  int dateMillis;

  int? dateSentMillis;

  int? subscriptionId;

  int? threadId;

  bool isRead;

  List<Object?> _toList() {
    return <Object?>[
      id,
      address,
      body,
      dateMillis,
      dateSentMillis,
      subscriptionId,
      threadId,
      isRead,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SmsMessageData decode(Object result) {
    result as List<Object?>;
    return SmsMessageData(
      id: result[0]! as int,
      address: result[1]! as String,
      body: result[2]! as String,
      dateMillis: result[3]! as int,
      dateSentMillis: result[4] as int?,
      subscriptionId: result[5] as int?,
      threadId: result[6] as int?,
      isRead: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SmsMessageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(address, other.address) &&
        _deepEquals(body, other.body) &&
        _deepEquals(dateMillis, other.dateMillis) &&
        _deepEquals(dateSentMillis, other.dateSentMillis) &&
        _deepEquals(subscriptionId, other.subscriptionId) &&
        _deepEquals(threadId, other.threadId) &&
        _deepEquals(isRead, other.isRead);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SmsMessageData(id: $id, address: $address, body: $body, dateMillis: $dateMillis, dateSentMillis: $dateSentMillis, subscriptionId: $subscriptionId, threadId: $threadId, isRead: $isRead)';
  }
}

class InboxQueryData {
  InboxQueryData({
    required this.afterId,
    required this.limit,
    this.sinceMillis,
    this.untilMillis,
    this.senders,
  });

  int afterId;

  int limit;

  int? sinceMillis;

  int? untilMillis;

  /// Lower-cased sender addresses; null or empty means all senders.
  List<String>? senders;

  List<Object?> _toList() {
    return <Object?>[afterId, limit, sinceMillis, untilMillis, senders];
  }

  Object encode() {
    return _toList();
  }

  static InboxQueryData decode(Object result) {
    result as List<Object?>;
    return InboxQueryData(
      afterId: result[0]! as int,
      limit: result[1]! as int,
      sinceMillis: result[2] as int?,
      untilMillis: result[3] as int?,
      senders: (result[4] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InboxQueryData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(afterId, other.afterId) &&
        _deepEquals(limit, other.limit) &&
        _deepEquals(sinceMillis, other.sinceMillis) &&
        _deepEquals(untilMillis, other.untilMillis) &&
        _deepEquals(senders, other.senders);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InboxQueryData(afterId: $afterId, limit: $limit, sinceMillis: $sinceMillis, untilMillis: $untilMillis, senders: $senders)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SmsMessageData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is InboxQueryData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SmsMessageData.decode(readValue(buffer)!);
      case 130:
        return InboxQueryData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SmsInboxHostApi {
  /// Constructor for [SmsInboxHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SmsInboxHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> hasPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sms_inbox.SmsInboxHostApi.hasPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> requestPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sms_inbox.SmsInboxHostApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<List<SmsMessageData>> query(InboxQueryData query) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sms_inbox.SmsInboxHostApi.query$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[query],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<SmsMessageData>();
  }
}
