// Copyright (c) 2026 Meheraj. Use of this source code is governed by the
// MIT license that can be found in the LICENSE file.
//
// Autogenerated from Pigeon, do not edit directly.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.meharaj007.sms_inbox

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class SmsMessageData (
  val id: Long,
  val address: String,
  val body: String,
  val dateMillis: Long,
  val dateSentMillis: Long? = null,
  val subscriptionId: Long? = null,
  val threadId: Long? = null,
  val isRead: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SmsMessageData {
      val id = pigeonVar_list[0] as Long
      val address = pigeonVar_list[1] as String
      val body = pigeonVar_list[2] as String
      val dateMillis = pigeonVar_list[3] as Long
      val dateSentMillis = pigeonVar_list[4] as Long?
      val subscriptionId = pigeonVar_list[5] as Long?
      val threadId = pigeonVar_list[6] as Long?
      val isRead = pigeonVar_list[7] as Boolean
      return SmsMessageData(id, address, body, dateMillis, dateSentMillis, subscriptionId, threadId, isRead)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      address,
      body,
      dateMillis,
      dateSentMillis,
      subscriptionId,
      threadId,
      isRead,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SmsMessageData
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.address, other.address) && MessagesPigeonUtils.deepEquals(this.body, other.body) && MessagesPigeonUtils.deepEquals(this.dateMillis, other.dateMillis) && MessagesPigeonUtils.deepEquals(this.dateSentMillis, other.dateSentMillis) && MessagesPigeonUtils.deepEquals(this.subscriptionId, other.subscriptionId) && MessagesPigeonUtils.deepEquals(this.threadId, other.threadId) && MessagesPigeonUtils.deepEquals(this.isRead, other.isRead)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.address)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.body)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.dateMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.dateSentMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subscriptionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.threadId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isRead)
    return result
  }
  override fun toString(): String {
    return "SmsMessageData(id=$id, address=$address, body=$body, dateMillis=$dateMillis, dateSentMillis=$dateSentMillis, subscriptionId=$subscriptionId, threadId=$threadId, isRead=$isRead)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InboxQueryData (
  val afterId: Long,
  val limit: Long,
  val sinceMillis: Long? = null,
  val untilMillis: Long? = null,
  /** Lower-cased sender addresses; null or empty means all senders. */
  val senders: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboxQueryData {
      val afterId = pigeonVar_list[0] as Long
      val limit = pigeonVar_list[1] as Long
      val sinceMillis = pigeonVar_list[2] as Long?
      val untilMillis = pigeonVar_list[3] as Long?
      val senders = pigeonVar_list[4] as List<String>?
      return InboxQueryData(afterId, limit, sinceMillis, untilMillis, senders)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      afterId,
      limit,
      sinceMillis,
      untilMillis,
      senders,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboxQueryData
    return MessagesPigeonUtils.deepEquals(this.afterId, other.afterId) && MessagesPigeonUtils.deepEquals(this.limit, other.limit) && MessagesPigeonUtils.deepEquals(this.sinceMillis, other.sinceMillis) && MessagesPigeonUtils.deepEquals(this.untilMillis, other.untilMillis) && MessagesPigeonUtils.deepEquals(this.senders, other.senders)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.afterId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.limit)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sinceMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.untilMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.senders)
    return result
  }
  override fun toString(): String {
    return "InboxQueryData(afterId=$afterId, limit=$limit, sinceMillis=$sinceMillis, untilMillis=$untilMillis, senders=$senders)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SmsMessageData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboxQueryData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SmsMessageData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is InboxQueryData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SmsInboxHostApi {
  fun hasPermission(): Boolean
  suspend fun requestPermission(): Boolean
  fun query(query: InboxQueryData): List<SmsMessageData>

  companion object {
    /** The codec used by SmsInboxHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SmsInboxHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SmsInboxHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sms_inbox.SmsInboxHostApi.hasPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasPermission())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sms_inbox.SmsInboxHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestPermission())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sms_inbox.SmsInboxHostApi.query$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as InboxQueryData
            val wrapped: List<Any?> = try {
              listOf(api.query(queryArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
